// https://docs.stripe.com/issuing/categories
export const MERCHANT_CATEGORIES: Record<string, string> = {
  ac_refrigeration_repair: "A/C, Refrigeration Repair",
  accounting_bookkeeping_services: "Accounting/Bookkeeping Services",
  advertising_services: "Advertising Services",
  agricultural_cooperative: "Agricultural Cooperative",
  airlines_air_carriers: "Airlines, Air Carriers",
  airports_flying_fields: "Airports, Flying Fields",
  ambulance_services: "Ambulance Services",
  amusement_parks_carnivals: "Amusement Parks/Carnivals",
  antique_reproductions: "Antique Reproductions",
  antique_shops: "Antique Shops",
  aquariums: "Aquariums",
  architectural_surveying_services: "Architectural/Surveying Services",
  art_dealers_and_galleries: "Art Dealers and Galleries",
  artists_supply_and_craft_shops: "Artists Supply and Craft Shops",
  auto_body_repair_shops: "Auto Body Repair Shops",
  auto_paint_shops: "Auto Paint Shops",
  auto_service_shops: "Auto Service Shops",
  auto_and_home_supply_stores: "Auto and Home Supply Stores",
  automated_cash_disburse: "Automated Cash Disburse",
  automated_fuel_dispensers: "Automated Fuel Dispensers",
  automobile_associations: "Automobile Associations",
  automotive_parts_and_accessories_stores:
    "Automotive Parts and Accessories Stores",
  automotive_tire_stores: "Automotive Tire Stores",
  bail_and_bond_payments:
    "Bail and Bond Payments (payment to the surety for the bond, not the actual bond paid to the government agency)",
  bakeries: "Bakeries",
  bands_orchestras: "Bands, Orchestras",
  barber_and_beauty_shops: "Barber and Beauty Shops",
  betting_casino_gambling: "Betting/Casino Gambling",
  bicycle_shops: "Bicycle Shops",
  billiard_pool_establishments: "Billiard/Pool Establishments",
  boat_dealers: "Boat Dealers",
  boat_rentals_and_leases: "Boat Rentals and Leases",
  book_stores: "Book Stores",
  books_periodicals_and_newspapers: "Books, Periodicals, and Newspapers",
  bowling_alleys: "Bowling Alleys",
  bus_lines: "Bus Lines",
  business_secretarial_schools: "Business/Secretarial Schools",
  buying_shopping_services: "Buying/Shopping Services",
  cable_satellite_and_other_pay_television_and_radio:
    "Cable, Satellite, and Other Pay Television and Radio",
  camera_and_photographic_supply_stores:
    "Camera and Photographic Supply Stores",
  candy_nut_and_confectionery_stores: "Candy, Nut, and Confectionery Stores",
  car_rental_agencies: "Car Rental Agencies",
  car_washes: "Car Washes",
  car_and_truck_dealers_new_used:
    "Car and Truck Dealers (New & Used) Sales, Service, Repairs Parts and Leasing",
  car_and_truck_dealers_used_only:
    "Car and Truck Dealers (Used Only) Sales, Service, Repairs Parts and Leasing",
  carpentry_services: "Carpentry Services",
  carpet_upholstery_cleaning: "Carpet/Upholstery Cleaning",
  caterers: "Caterers",
  charitable_and_social_service_organizations_fundraising:
    "Charitable and Social Service Organizations - Fundraising",
  chemicals_and_allied_products: "Chemicals and Allied Products",
  child_care_services: "Child Care Services",
  childrens_and_infants_wear_stores: "Childrens and Infants Wear Stores",
  chiropodists_podiatrists: "Chiropodists, Podiatrists",
  chiropractors: "Chiropractors",
  cigar_stores_and_stands: "Cigar Stores and Stands",
  civic_social_fraternal_associations: "Civic, Social, Fraternal Associations",
  cleaning_and_maintenance: "Cleaning and Maintenance",
  clothing_rental: "Clothing Rental",
  colleges_universities: "Colleges, Universities",
  commercial_equipment: "Commercial Equipment",
  commercial_footwear: "Commercial Footwear",
  commercial_photography_art_and_graphics:
    "Commercial Photography, Art and Graphics",
  commuter_transport_and_ferries: "Commuter Transport, Ferries",
  computer_network_services: "Computer Network Services",
  computer_programming: "Computer Programming",
  computer_repair: "Computer Repair",
  computer_software_stores: "Computer Software Stores",
  computers_peripherals_and_software: "Computers, Peripherals, and Software",
  concrete_work_services: "Concrete Work Services",
  construction_materials: "Construction Materials",
  consulting_public_relations: "Consulting, Public Relations",
  correspondence_schools: "Correspondence Schools",
  cosmetic_stores: "Cosmetic Stores",
  counseling_services: "Counseling Services",
  country_clubs: "Country Clubs",
  courier_services: "Courier Services",
  court_costs:
    "Court Costs, Including Alimony and Child Support - Courts of Law",
  credit_reporting_agencies: "Credit Reporting Agencies",
  cruise_lines: "Cruise Lines",
  dairy_products_stores: "Dairy Products Stores",
  dance_hall_studios_schools: "Dance Hall, Studios, Schools",
  dating_escort_services: "Dating/Escort Services",
  dentists_orthodontists: "Dentists, Orthodontists",
  department_stores: "Department Stores",
  detective_agencies: "Detective Agencies",
  digital_goods_media: "Digital Goods Media – Books, Movies, Music",
  digital_goods_applications: "Digital Goods – Applications (Excludes Games)",
  digital_goods_games: "Digital Goods – Games",
  digital_goods_large_volume: "Digital Goods – Large Digital Goods Merchant",
  direct_marketing_catalog_merchant: "Direct Marketing - Catalog Merchant",
  direct_marketing_combination_catalog_and_retail_merchant:
    "Direct Marketing - Combination Catalog and Retail Merchant",
  direct_marketing_inbound_telemarketing:
    "Direct Marketing - Inbound Telemarketing",
  direct_marketing_insurance_services: "Direct Marketing - Insurance Services",
  direct_marketing_other: "Direct Marketing - Other",
  direct_marketing_outbound_telemarketing:
    "Direct Marketing - Outbound Telemarketing",
  direct_marketing_subscription: "Direct Marketing - Subscription",
  direct_marketing_travel: "Direct Marketing - Travel",
  discount_stores: "Discount Stores",
  doctors: "Doctors",
  door_to_door_sales: "Door-To-Door Sales",
  drapery_window_covering_and_upholstery_stores:
    "Drapery, Window Covering, and Upholstery Stores",
  drinking_places: "Drinking Places",
  drug_stores_and_pharmacies: "Drug Stores and Pharmacies",
  drugs_drug_proprietaries_and_druggist_sundries:
    "Drugs, Drug Proprietaries, and Druggist Sundries",
  dry_cleaners: "Dry Cleaners",
  durable_goods: "Durable Goods",
  duty_free_stores: "Duty Free Stores",
  eating_places_restaurants: "Eating Places, Restaurants",
  educational_services: "Educational Services",
  electric_razor_stores: "Electric Razor Stores",
  electric_vehicle_charging: "Electric Vehicle Charging",
  electrical_parts_and_equipment: "Electrical Parts and Equipment",
  electrical_services: "Electrical Services",
  electronics_repair_shops: "Electronics Repair Shops",
  electronics_stores: "Electronics Stores",
  elementary_secondary_schools: "Elementary, Secondary Schools",
  emergency_services_gcas_visa_use_only:
    "Emergency Services (GCAS) (Visa use only)",
  employment_temp_agencies: "Employment/Temp Agencies",
  equipment_rental: "Equipment Rental",
  exterminating_services: "Exterminating Services",
  family_clothing_stores: "Family Clothing Stores",
  fast_food_restaurants: "Fast Food Restaurants",
  financial_institutions: "Financial Institutions",
  fines_government_administrative_entities:
    "Fines - Government Administrative Entities",
  fireplace_fireplace_screens_and_accessories_stores:
    "Fireplace, Fireplace Screens, and Accessories Stores",
  floor_covering_stores: "Floor Covering Stores",
  florists: "Florists",
  florists_supplies_nursery_stock_and_flowers:
    "Florists Supplies, Nursery Stock, and Flowers",
  freezer_and_locker_meat_provisioners: "Freezer and Locker Meat Provisioners",
  fuel_dealers_non_automotive: "Fuel Dealers (Non Automotive)",
  funeral_services_crematories: "Funeral Services, Crematories",
  furniture_repair_refinishing: "Furniture Repair, Refinishing",
  furniture_home_furnishings_and_equipment_stores_except_appliances:
    "Furniture, Home Furnishings, and Equipment Stores, Except Appliances",
  furriers_and_fur_shops: "Furriers and Fur Shops",
  general_services: "General Services",
  gift_card_novelty_and_souvenir_shops:
    "Gift, Card, Novelty, and Souvenir Shops",
  glass_paint_and_wallpaper_stores: "Glass, Paint, and Wallpaper Stores",
  glassware_crystal_stores: "Glassware, Crystal Stores",
  golf_courses_public: "Golf Courses - Public",
  government_licensed_online_casions_online_gambling_us_region_only:
    "Government Licensed On-line Casinos (On-Line Gambling)(US Region only)",
  government_services: "Government Services",
  government_licensed_horse_dog_racing_us_region_only:
    "Government-Licensed Horse/Dog Racing (US Region only)",
  government_owned_lotteries_non_us_region:
    "Government-Owned Lotteries (Non-US region)",
  government_owned_lotteries_us_region_only:
    "Government-Owned Lotteries (US Region only)",
  grocery_stores_supermarkets: "Grocery Stores, Supermarkets",
  hardware_stores: "Hardware Stores",
  hardware_equipment_and_supplies: "Hardware, Equipment, and Supplies",
  health_and_beauty_spas: "Health and Beauty Spas",
  hearing_aids_sales_and_supplies: "Hearing Aids Sales and Supplies",
  heating_plumbing_a_c: "Heating, Plumbing, A/C",
  hobby_toy_and_game_shops: "Hobby, Toy, and Game Shops",
  home_supply_warehouse_stores: "Home Supply Warehouse Stores",
  hospitals: "Hospitals",
  hotels_motels_and_resorts: "Hotels, Motels, and Resorts",
  household_appliance_stores: "Household Appliance Stores",
  industrial_supplies: "Industrial Supplies",
  information_retrieval_services: "Information Retrieval Services",
  insurance_default: "Insurance - Default",
  insurance_underwriting_premiums: "Insurance Underwriting, Premiums",
  intra_company_purchases: "Intra-Company Purchases",
  jewelry_stores_watches_clocks_and_silverware_stores:
    "Jewelry Stores, Watches, Clocks, and Silverware Stores",
  landscaping_services: "Landscaping Services",
  laundries: "Laundries",
  laundry_cleaning_services: "Laundry, Cleaning Services",
  legal_services_attorneys: "Legal Services, Attorneys",
  luggage_and_leather_goods_stores: "Luggage and Leather Goods Stores",
  lumber_building_materials_stores: "Lumber, Building Materials Stores",
  manual_cash_disburse: "Manual Cash Disburse",
  marinas_service_and_supplies: "Marinas, Service and Supplies",
  marketplaces: "Marketplaces",
  masonry_stonework_and_plaster: "Masonry, Stonework, and Plaster",
  massage_parlors: "Massage Parlors",
  medical_services: "Medical Services",
  medical_and_dental_labs: "Medical and Dental Labs",
  medical_dental_ophthalmic_and_hospital_equipment_and_supplies:
    "Medical, Dental, Ophthalmic, and Hospital Equipment and Supplies",
  membership_organizations: "Membership Organizations",
  mens_and_boys_clothing_and_accessories_stores:
    "Mens and Boys Clothing and Accessories Stores",
  mens_womens_clothing_stores: "Mens, Womens Clothing Stores",
  metal_service_centers: "Metal Service Centers",
  miscellaneous_apparel_and_accessory_shops:
    "Miscellaneous Apparel and Accessory Shops",
  miscellaneous_auto_dealers: "Miscellaneous Auto Dealers",
  miscellaneous_business_services: "Miscellaneous Business Services",
  miscellaneous_food_stores:
    "Miscellaneous Food Stores - Convenience Stores and Specialty Markets",
  miscellaneous_general_merchandise: "Miscellaneous General Merchandise",
  miscellaneous_general_services: "Miscellaneous General Services",
  miscellaneous_home_furnishing_specialty_stores:
    "Miscellaneous Home Furnishing Specialty Stores",
  miscellaneous_publishing_and_printing:
    "Miscellaneous Publishing and Printing",
  miscellaneous_recreation_services: "Miscellaneous Recreation Services",
  miscellaneous_repair_shops: "Miscellaneous Repair Shops",
  miscellaneous_specialty_retail: "Miscellaneous Specialty Retail",
  mobile_home_dealers: "Mobile Home Dealers",
  motion_picture_theaters: "Motion Picture Theaters",
  motor_freight_carriers_and_trucking:
    "Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services",
  motor_homes_dealers: "Motor Homes Dealers",
  motor_vehicle_supplies_and_new_parts: "Motor Vehicle Supplies and New Parts",
  motorcycle_shops_and_dealers: "Motorcycle Shops and Dealers",
  motorcycle_shops_dealers: "Motorcycle Shops, Dealers",
  music_stores_musical_instruments_pianos_and_sheet_music:
    "Music Stores-Musical Instruments, Pianos, and Sheet Music",
  news_dealers_and_newsstands: "News Dealers and Newsstands",
  non_fi_money_orders: "Non-FI, Money Orders",
  non_fi_stored_value_card_purchase_load:
    "Non-FI, Stored Value Card Purchase/Load",
  nondurable_goods: "Nondurable Goods",
  nurseries_lawn_and_garden_supply_stores:
    "Nurseries, Lawn and Garden Supply Stores",
  nursing_personal_care: "Nursing/Personal Care",
  office_and_commercial_furniture: "Office and Commercial Furniture",
  opticians_eyeglasses: "Opticians, Eyeglasses",
  optometrists_ophthalmologist: "Optometrists, Ophthalmologist",
  orthopedic_goods_prosthetic_devices: "Orthopedic Goods - Prosthetic Devices",
  osteopaths: "Osteopaths",
  package_stores_beer_wine_and_liquor: "Package Stores-Beer, Wine, and Liquor",
  paints_varnishes_and_supplies: "Paints, Varnishes, and Supplies",
  parking_lots_garages: "Parking Lots, Garages",
  passenger_railways: "Passenger Railways",
  pawn_shops: "Pawn Shops",
  pet_shops_pet_food_and_supplies: "Pet Shops, Pet Food, and Supplies",
  petroleum_and_petroleum_products: "Petroleum and Petroleum Products",
  photo_developing: "Photo Developing",
  photographic_studios: "Photographic Studios",
  photographic_photocopy_microfilm_equipment_and_supplies:
    "Photographic, Photocopy, Microfilm Equipment, and Supplies",
  picture_video_production: "Picture/Video Production",
  piece_goods_notions_and_other_dry_goods:
    "Piece Goods, Notions, and Other Dry Goods",
  plumbing_heating_equipment_and_supplies:
    "Plumbing, Heating Equipment, and Supplies",
  political_organizations: "Political Organizations",
  postal_services_government_only: "Postal Services - Government Only",
  precious_stones_and_metals_watches_and_jewelry:
    "Precious Stones and Metals, Watches and Jewelry",
  professional_services: "Professional Services",
  public_warehousing_and_storage:
    "Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage",
  quick_copy_repro_and_blueprint: "Quick Copy, Repro, and Blueprint",
  railroads: "Railroads",
  real_estate_agents_and_managers_rentals:
    "Real Estate Agents and Managers - Rentals",
  record_stores: "Record Stores",
  recreational_vehicle_rentals: "Recreational Vehicle Rentals",
  religious_goods_stores: "Religious Goods Stores",
  religious_organizations: "Religious Organizations",
  roofing_siding_sheet_metal: "Roofing/Siding, Sheet Metal",
  secretarial_support_services: "Secretarial Support Services",
  security_brokers_dealers: "Security Brokers/Dealers",
  service_stations: "Service Stations",
  sewing_needlework_fabric_and_piece_goods_stores:
    "Sewing, Needlework, Fabric, and Piece Goods Stores",
  shoe_repair_hat_cleaning: "Shoe Repair/Hat Cleaning",
  shoe_stores: "Shoe Stores",
  small_appliance_repair: "Small Appliance Repair",
  snowmobile_dealers: "Snowmobile Dealers",
  special_trade_services: "Special Trade Services",
  specialty_cleaning: "Specialty Cleaning",
  sporting_goods_stores: "Sporting Goods Stores",
  sporting_recreation_camps: "Sporting/Recreation Camps",
  sports_clubs_fields: "Sports Clubs/Fields",
  sports_and_riding_apparel_stores: "Sports and Riding Apparel Stores",
  stamp_and_coin_stores: "Stamp and Coin Stores",
  stationary_office_supplies_printing_and_writing_paper:
    "Stationary, Office Supplies, Printing and Writing Paper",
  stationery_stores_office_and_school_supply_stores:
    "Stationery Stores, Office, and School Supply Stores",
  swimming_pools_sales: "Swimming Pools Sales",
  t_ui_travel_germany: "TUI Travel - Germany",
  tailors_alterations: "Tailors, Alterations",
  tax_payments_government_agencies: "Tax Payments - Government Agencies",
  tax_preparation_services: "Tax Preparation Services",
  taxicabs_limousines: "Taxicabs/Limousines",
  telecommunication_equipment_and_telephone_sales:
    "Telecommunication Equipment and Telephone Sales",
  telecommunication_services: "Telecommunication Services",
  telegraph_services: "Telegraph Services",
  tent_and_awning_shops: "Tent and Awning Shops",
  testing_laboratories: "Testing Laboratories",
  theatrical_ticket_agencies: "Theatrical Ticket Agencies",
  timeshares: "Timeshares",
  tire_retreading_and_repair: "Tire Retreading and Repair",
  tolls_bridge_fees: "Tolls/Bridge Fees",
  tourist_attractions_and_exhibits: "Tourist Attractions and Exhibits",
  towing_services: "Towing Services",
  trailer_parks_campgrounds: "Trailer Parks, Campgrounds",
  transportation_services: "Transportation Services",
  travel_agencies_tour_operators: "Travel Agencies, Tour Operators",
  truck_stop_iteration: "Truck Stops",
  truck_utility_trailer_rentals: "Truck/Utility Trailer Rentals",
  typesetting_plate_making_and_related_services:
    "Typesetting, Plate Making, and Related Services",
  typewriter_stores: "Typewriter Stores",
  u_s_federal_government_agencies_or_departments:
    "U.S. Federal Government Agencies or Departments",
  uniforms_commercial_clothing: "Uniforms, Commercial Clothing",
  used_merchandise_and_secondhand_stores:
    "Used Merchandise and Secondhand Stores",
  utilities: "Utilities",
  variety_stores: "Variety Stores",
  veterinary_services: "Veterinary Services",
  video_amusement_game_supplies: "Video Amusement Game Supplies",
  video_game_arcades: "Video Game Arcades",
  video_tape_rental_stores: "Video Tape Rental Stores",
  vocational_trade_schools: "Vocational/Trade Schools",
  watch_jewelry_repair: "Watch/Jewelry Repair",
  welding_repair: "Welding Repair",
  wholesale_clubs: "Wholesale Clubs",
  wig_and_toupee_stores: "Wig and Toupee Stores",
  wires_money_orders: "Wires, Money Orders",
  womens_accessory_and_specialty_shops: "Womens Accessory and Specialty Shops",
  womens_ready_to_wear_stores: "Womens Ready-To-Wear Stores",
  wrecking_and_salvage_yards: "Wrecking and Salvage Yards",
};

export const CHART_COLORS = ["cyan", "blue", "indigo", "violet", "fuchsia"];
export const CHART_MIN_SHARE = 5;
